CREATE TABLE person(
                       id         bigserial PRIMARY KEY NOT NULL,
                       first_name varchar(255)          NOT NULL,
                       last_name  varchar(255)          NOT NULL,
                       reg_date   timestamp             NOT NULL,
                       birth_date timestamp             NULL,
                       e_mail     varchar(255)          NOT NULL,
                       phone      varchar(255)          NULL,
                       "password" varchar(255)          NOT NULL,
                       photo      varchar(255)          NULL,
                       about      text                  NULL,
                       city       varchar(255)          NULL,
	country varchar(255) NULL,
	confirmation_code varchar(255) NULL,
	is_approved int4 NULL,
	messages_permission varchar(255) NULL,
	last_online_time timestamp NULL,
	is_blocked int4 NULL,
	is_online int4 NULL,
	is_deleted int4 NULL
);