insert into post (id, time, author_id, is_blocked, is_deleted, title, post_text) values (1, '2020-07-23 00:05:52', 1, 0, 0, 'Hello', 'Brand is just a perception, and perception will match reality over time. Sometimes it will be ahead, other times it will be behind. But brand is simply a collective impression some have about a product.');
insert into post (id, time, author_id, is_blocked, is_deleted, title, post_text) values (2, '2020-07-24 01:02:51', 1, 0, 0, 'How are you doing?', 'It is a mistake to hire huge numbers of people to get a complicated job done. Numbers will never compensate for talent in getting the right answer (two people who dont know something are no better than one), will tend to slow down progress, and will make the task incredibly expensive.');
insert into post (id, time, author_id, is_blocked, is_deleted, title, post_text) values (3, '2020-10-12 21:42:15', 2, 0, 0, 'Эххх', 'Я мечтаю сто дней быть никем. Сто дней вообще забыть все. Как бомж, вон там бросить телогрейку и под солнышком поваляться.');
insert into post (id, time, author_id, is_blocked, is_deleted, title, post_text) values (4, '2020-11-14 20:02:32', 2, 0, 0, 'Не, ну а че', 'Надо заставить правительство прекратить этот перелёт птиц! Эту песенку нужно поломать! Никаких перелетов больше на север! Пускай там на юге остаются! Отстрелять всех птиц. Поставить всех наших мужчин, войска от Сочи до Крыма, и любые перелётные птицы должны остаться на том месте, где находятся! Это не шутки! Это самый современный способ ведения войны. Когда они такие безобидные птички летят по какой-то стране, и потом полстраны остаются без продовольствия, а часть людей умирает');
insert into post (id, time, author_id, is_blocked, is_deleted, title, post_text) values (5, '2020-12-02 10:05:31', 3, 0, 0, 'Кря', 'Весь мир испытывает коллективный экзистенциальный кризис. Лежишь ты сейчас такой несчастный, думаешь о смысле своего бытия. «Я не живу — я существую». Через тысячелетия наши потомки будут цитировать эту фразу, как мы сегодня: «Cogito ergo sum»');
insert into post (id, time, author_id, is_blocked, is_deleted, title, post_text) values (6, '2020-12-02 14:13:13', 3, 0, 0, 'Эзюпери', 'Что порадует людей, затерявшихся в мелькании недель, в слепых годах без праздников? Людей, позабывших благородную иерархию, ненавидящих успех соседа и желающих одного: чтобы все вокруг были одинаково несчастны? Люди эти создали смрадное болото, так откуда придет к ним радость?');

insert into post_comment (id, time, author_id, post_id, is_blocked, is_deleted, comment_text) values (1, '2020-12-01 10:13:13', 2, 1, 0, 0, 'чооооо?');
insert into post_comment (id, time, author_id, post_id, is_blocked, is_deleted, comment_text) values (2, '2020-12-01 10:14:14', 2, 2, 0, 0, 'пиши по руски, нууу!');
insert into post_comment (id, time, author_id, post_id, is_blocked, is_deleted, comment_text) values (3, '2020-12-01 11:11:13', 3, 2, 0, 0, 'So smart!');
insert into post_comment (id, time, author_id, post_id, parent_id, is_blocked, is_deleted, comment_text) values (4, '2020-12-01 14:12:33', 3, 2, 2, 0, 0, 'Правильно "по русский"...');
insert into post_comment (id, time, author_id, post_id, parent_id, is_blocked, is_deleted, comment_text) values (5, '2020-12-01 15:13:13', 1, 2, 2, 0, 0, 'i''m OK, thanks');
insert into post_comment (id, time, author_id, post_id, is_blocked, is_deleted, comment_text) values (6, '2020-12-01 14:13:13', 3, 3, 0, 0, 'facepalm');
insert into post_comment (id, time, author_id, post_id, is_blocked, is_deleted, comment_text) values (7, '2020-12-01 15:22:17', 3, 4, 0, 0, 'болван');
insert into post_comment (id, time, author_id, post_id, is_blocked, is_deleted, comment_text) values (8, '2020-12-01 12:22:17', 2, 6, 0, 0, 'а твоей маме зять не нужэн?');
insert into post_comment (id, time, author_id, post_id, is_blocked, is_deleted, comment_text) values (9, '2020-12-01 13:22:11', 2, 5, 0, 0, 'умная штоль? Поехали лучше пива попьем!');
insert into post_comment (id, time, author_id, post_id, parent_id, is_blocked, is_deleted, comment_text) values (10, '2020-12-01 14:20:11', 3, 5, 9, 0, 0, 'чтобы я... с таким... да еще и пиво? Немыслимо!');
insert into post_comment (id, time, author_id, post_id, parent_id, is_blocked, is_deleted, comment_text) values (11, '2020-12-01 14:23:12', 2, 5, 10, 0, 0, 'ой да ладно ломаться, нууу');
